### ISSUE TITLE
Textures are created and destroyed again

### ISSUE THREAD

**Issue by jorgdebont** [ThomasvLingen/Minor_vidya#51]
Textures in SDLfacade should not be created and destroyed with every draw text

EDIT:
After some discussion, this was ruled out for draw_text calls.

**Comment by Mfrielink** [comment]
Your idea is to only create a texture when it is first drawn and destroy it once it is no longer needed, to prevent the constant re-creation and destruction of basically the same texture, am I right?

**Comment by jorgdebont** [comment]
@Mfrielink Yes this is correct, or perhaps create it before in an init

**Comment by Mfrielink** [comment]
After some discussion we concluded not to infest any time in this until it becomes a problem. The amount of effort necessary in order to changes our way of dealing with textures is not worth to result at the moment.

**Comment by ThomasvLingen** [comment]
I'd like this to be a more specific issue, the only thing we ruled out was to do this for draw_text calls.

I, however, still find this a very valid thing to do for image_draws. Currently, whenever an image is drawn (60 times per second in a menu) a IMG_Load call is done to create the texture. For images, since these are static and will not change(unlike text), we can just store these textures in a map<string, SDL_Texture*> (filename mapped to texture).

**Comment by ThomasvLingen** [comment]
The image thing was fixed by @SandervGeel in #101
